import XCTest

/// The "current" side is a pre-baked `CodeArtifact` fixture (`seeded-with-added.json`, generated by
/// `FixtureArtifactGeneratorTests`) that already includes an `Added` type, and the "HEAD" comparison
/// side is a separate pre-baked fixture (`comparison-HEAD.json`) without it — so comparing the two
/// produces a real, visible delta without a real git commit or a real parse. That comparing against
/// HEAD excludes an uncommitted addition is covered at the ViewModel layer by
/// `PullRequestComparisonTests.comparingAgainstHEADExcludesAnUncommittedAddition`; this journey only
/// verifies the panel renders and interacts correctly once that state exists.
@MainActor
final class CompareGitRevisionTests: UIJourneyTestCase {
    func testComparingAgainstHEADShowsTheAddedTypeAsADelta() throws {
        let codebaseDetail = openPreindexedSeededCodebase(analysis: .preindexedComparedWithHEAD)
        let diagram = codebaseDetail.createDiagram(type: "class", as: ClassDiagramScreen.self)

        diagram.typeNode(named: "Added").waitOrFail("the Added type on the current side", timeout: .uiWork)
        diagram.tapFitToView()

        diagram.openCompare()
        validateScreenshot("ClassDiagram", state: "comparePanelOpen")

        diagram.compare(against: "HEAD")
        let findingsSummary = diagram.compareFindingsSummary.waitOrFail("the compare panel's findings summary")
        findingsSummary.waitUntilFrameStable("the compare panel's findings summary")
        // This capture carries far more on-screen text than any other screenshot in the suite —
        // section headers, counts, and disclosure chevrons for three findings groups — and #396's
        // pixel forensics (CI artifact diffed against the golden, byte-for-byte) found the resulting
        // drift is independent per-glyph CoreText/SF Symbols antialiasing noise between app launches:
        // no content, layout, or color differs, and no whole- or sub-pixel shift aligns the images
        // any better than zero offset. Observed drift across many unrelated CI runs has ranged
        // 0.0000%–0.2823%; 0.5% clears that noise ceiling with real margin while still catching an
        // actual regression, which would move far more than a thin glyph-edge outline.
        validateScreenshot("ClassDiagram", state: "deltaComparison", maxChangedFraction: 0.005)

        // Clear disables the comparison directly — there's no "None" row to pick instead.
        diagram.compareClearButton.tapWhenReady("the compare panel's Clear button")
        diagram.compareOperation.loaded.waitForDisappearanceOrFail("the loaded comparison after Clear")
    }
}
