import XCTest

/// The "current" side is a pre-baked `CodeArtifact` fixture (`seeded-with-added.json`, generated by
/// `FixtureArtifactGeneratorTests`) that already includes an `Added` type, and the "HEAD" comparison
/// side is a separate pre-baked fixture (`comparison-HEAD.json`) without it — so comparing the two
/// produces a real, visible delta without a real git commit or a real parse. That comparing against
/// HEAD excludes an uncommitted addition is covered at the ViewModel layer by
/// `PullRequestComparisonTests.comparingAgainstHEADExcludesAnUncommittedAddition`; this journey only
/// verifies the panel renders and interacts correctly once that state exists.
@MainActor
final class CompareGitRevisionTests: UIJourneyTestCase {
    func testComparingAgainstHEADShowsTheAddedTypeAsADelta() throws {
        let codebaseDetail = openPreindexedSeededCodebase(analysis: .preindexedComparedWithHEAD)
        let diagram = codebaseDetail.createDiagram(type: "class", as: ClassDiagramScreen.self)

        diagram.typeNode(named: "Added").waitOrFail("the Added type on the current side", timeout: .uiWork)
        diagram.tapFitToView()

        diagram.openCompare()
        validateScreenshot("ClassDiagram", state: "comparePanelOpen")

        diagram.compare(against: "HEAD")
        let findingsSummary = diagram.compareFindingsSummary.waitOrFail("the compare panel's findings summary")
        // Existing doesn't imply settled: `isFullyLoaded` inserts this element below a ref list whose
        // own height is a flexible 150–260pt range (`CompareGitOverlay.swift`), so the panel can still
        // be renegotiating that range — moving this very element — for a render pass or two after it
        // first appears (#396). A screenshot taken the instant it exists can land mid-renegotiation
        // and drift by a sub-pixel amount from run to run; wait for its own frame to stop moving first.
        findingsSummary.waitUntilFrameStable("the compare panel's findings summary")
        validateScreenshot("ClassDiagram", state: "deltaComparison")

        // Clear disables the comparison directly — there's no "None" row to pick instead.
        diagram.compareClearButton.tapWhenReady("the compare panel's Clear button")
        diagram.compareOperation.loaded.waitForDisappearanceOrFail("the loaded comparison after Clear")
    }
}
