classDiagram
    class Python_Library["Library"] {
        +playlists list~Playlist~
        +__init__(playlists list~Playlist~?)
        +addPlaylist(playlist Playlist) None
        +playlist(named str) Playlist?
    }
    class Python_MediaItem["MediaItem"] {
        +title str
        +duration float
        +genre Genre
        +__init__(title str, duration float, genre Genre)
        +play() None
    }
    class Python_Playable["Playable"] {
        <<interface>>
        +title str
        +duration float
        +play() None
    }
    class Python_Genre["Genre"] {
        <<enumeration>>
        POP
        ROCK
        JAZZ
        CLASSICAL
        ELECTRONIC
        SPOKEN_WORD
    }
    class Python_Player["Player"] {
        +library Library
        +nowPlaying Playable?
        +__init__(library Library)
        +play(item Playable) None
        +playFirstItem(playlistNamed str) None
    }
    class Python_Playlist["Playlist"] {
        +name str
        +items list~MediaItem~
        +totalDuration float
        +__init__(name str, items list~MediaItem~?)
        +add(item MediaItem) None
    }
    class Python_Podcast["Podcast"] {
        +host str
        +episodeNumber int
        +__init__(title str, duration float, host str, episodeNumber int)
        +play() None
    }
    class Python_Song["Song"] {
        +artist str
        +album str?
        +__init__(title str, duration float, genre Genre, artist str, album str?)
        +play() None
    }
    Python_Playable <|.. Python_MediaItem
    Python_MediaItem <|-- Python_Podcast
    Python_MediaItem <|-- Python_Song
    Python_Library o-- "*" Python_Playlist : playlists
    Python_MediaItem *-- "1" Python_Genre : genre
    Python_Player *-- "1" Python_Library : library
    Python_Player *-- "0..1" Python_Playable : nowPlaying
    Python_Playlist o-- "*" Python_MediaItem : items
    Python_Song ..> Python_Genre
