classDiagram
    class TypeScript_Library["Library"] {
        +playlists Playlist[]
        +constructor(playlists Playlist[])
        +addPlaylist(playlist Playlist) void
        +playlist(named string) Playlist | undefined
    }
    class TypeScript_MediaItem["MediaItem"] {
        +title string
        +duration number
        +genre Genre
        +constructor(title string, duration number, genre Genre)
        +play() void
    }
    class TypeScript_Playable["Playable"] {
        <<interface>>
        +title string
        +duration number
        +play() void
    }
    class TypeScript_Genre["Genre"] {
        <<enumeration>>
        Pop
        Rock
        Jazz
        Classical
        Electronic
        SpokenWord
    }
    class TypeScript_Player["Player"] {
        -nowPlaying Playable | null
        -library Library
        +constructor(library Library)
        +play(item Playable) void
        +playFirstItem(playlistNamed string) void
    }
    class TypeScript_Playlist["Playlist"] {
        +name string
        +items MediaItem[]
        +totalDuration number
        +constructor(name string, items MediaItem[])
        +add(item MediaItem) void
    }
    class TypeScript_Podcast["Podcast"] {
        +host string
        +episodeNumber number
        +constructor(title string, duration number, host string, episodeNumber number)
        +play() void
    }
    class TypeScript_Song["Song"] {
        +artist string
        +album string
        +constructor(title string, duration number, genre Genre, artist string, album string?)
        +play() void
    }
    TypeScript_Playable <|.. TypeScript_MediaItem
    TypeScript_MediaItem <|-- TypeScript_Podcast
    TypeScript_MediaItem <|-- TypeScript_Song
    TypeScript_Library o-- "*" TypeScript_Playlist : playlists
    TypeScript_MediaItem *-- "1" TypeScript_Genre : genre
    TypeScript_Player *-- "1" TypeScript_Library : library
    TypeScript_Player ..> TypeScript_Playable
    TypeScript_Playlist o-- "*" TypeScript_MediaItem : items
    TypeScript_Song ..> TypeScript_Genre
