import AcaiCore

/// Infers a *candidate* `quality.yml` from the current graph so adopting `acai quality` is "review
/// and edit a draft" rather than "author from a blank page". A value you instantiate from a
/// `GraphView` and ask for its `yaml`: the module-cycle invariant (or, when the graph already has
/// cycles, those cycles as commented known-debt), plus metric budgets seeded from the *current*
/// observed maxima so the file ratchets against regression from day one.
///
/// Language-agnostic: it reads only the graph's metrics and provenance-aware module cycles, naming no
/// language or framework. Output is authored as heavily-commented YAML in the house style; the active
/// sections re-parse via `QualityRules.load`.
public struct StarterQualityRules {
    private let graph: GraphView
    private let moduleCycles: [CycleFinder.Cycle]

    public init(graph: GraphView, moduleResolver: ModuleResolver = .standard) {
        self.graph = graph
        self.moduleCycles = CycleFinder(graph: graph, moduleResolver: moduleResolver).cycles(scope: .modules)
    }

    /// The generated draft as a YAML string.
    public var yaml: String {
        (header + cyclesSection + budgetsSection + smellHints).joined(separator: "\n") + "\n"
    }

    private var header: [String] {
        [
            "# Candidate code-quality contract — generated by `acai rules init`.",
            "#   acai quality --source . --rules quality.yml",
            "#",
            "# A DRAFT: review and tighten every threshold before committing. Budgets are seeded from the",
            "# current worst-case value (no headroom) so the file blocks regression immediately; ratchet",
            "# them down as debt is paid off.",
            ""
        ]
    }

    /// The acyclic invariant when the module graph is clean; otherwise the current cycles listed as
    /// commented known-debt (so an initial `check` isn't dead-on-arrival against pre-existing cycles).
    private var cyclesSection: [String] {
        guard moduleCycles.isEmpty else {
            return [
                "# The module graph currently has cycles — break these, then enable the invariant below:",
                "# cycles:",
                "#   scope: modules"
            ] + moduleCycles.map { "#   known debt: \($0.description)" } + [""]
        }
        return [
            "# Hard invariant: the module dependency graph must stay acyclic.",
            "cycles:",
            "  scope: modules",
            ""
        ]
    }

    private var budgetsSection: [String] {
        let budgets = seededBudgets
        guard !budgets.isEmpty else { return [] }
        return ["# Per-type budgets, seeded from current maxima — tighten as you pay down debt.", "budgets:"]
            + budgets.flatMap { $0.lines } + [""]
    }

    /// One budget per structural metric that has a positive current maximum.
    private var seededBudgets: [SeededBudget] {
        let types = graph.metrics.types
        return [
            SeededBudget(metric: "fanOut", max: types.map(\.fanOut).max() ?? 0,
                         message: "Type depends on too many others — a responsibility-bloat / splitting candidate."),
            SeededBudget(metric: "fanIn", max: types.map(\.fanIn).max() ?? 0,
                         message: "Over-central hub type — keep it stable and well-tested."),
            SeededBudget(metric: "weightedMethods", max: types.map(\.weightedMethods).max() ?? 0,
                         message: "God class: too many methods — split responsibilities (SRP).")
        ].filter { $0.max > 0 }
    }

    /// Commented pointers to the code-smell budgets, annotated with the current maximum so the reader
    /// can pick an informed ceiling. Kept commented because a good threshold is a judgement call.
    private var smellHints: [String] {
        let types = graph.metrics.types
        let rfc = types.map(\.responseForClass).max() ?? 0
        let lcom = types.map(\.lackOfCohesion).max() ?? 0
        return [
            "# Code-smell budgets (currently just hints — uncomment and set a ceiling to enforce):",
            "#  - metric: rfc            # response set; max seen: \(rfc)",
            "#    max: \(rfc)",
            "#  - metric: lcom           # LCOM4 components; max seen: \(lcom)",
            "#    max: \(lcom)",
            "#  - metric: mutablePublicState   # publicly settable stored properties (encapsulation leak)",
            "#    max: 0"
        ]
    }
}

/// A single seeded budget rendered as YAML lines.
private struct SeededBudget {
    let metric: String
    let max: Int
    let message: String

    var lines: [String] {
        [
            "  - metric: \(metric)",
            "    max: \(max)",
            "    message: \"\(message)\""
        ]
    }
}
